### ISSUE TITLE
Plan Growth based on Blocks

### ISSUE THREAD

**Issue by yuyangz** [yuyangz/CareBears#1]
The area in which a block can be grown is not correct.
While the average water in a block may be above 0, it sometimes still grows.

**Comment by yuyangz** [comment]
Occasional OutOfBoundsExceptions

**Comment by ibnullify** [comment]
I'm not exactly sure what you mean Yuyang
We should limit plant growth based on water in a gridblock as our next thing, but I'm not sure what you mean by _The area in which a block can be grown is not correct._
