### ISSUE TITLE
Plant Overlap

### ISSUE THREAD

**Issue by yuyangz** [yuyangz/CareBears#2]
Figure out a way to make it so plants do not overlap.
- Perhaps we can place a grid system so limit the places where people can place plants?
        - This grid system can be similar to the one we use for showRain. Therefore only one plant can be   
           grown on each block and each avgwater will correspond to one plant.
- Use distance to check if two plants are touching. If so, decrease the size of both of them?
        - This will require centering each block for avgwater on the position of the new plant. 
           ex. If block (1,1) originally was 50 up and 50 across, having a plant on the coordinates (26,26),  
           will require the block to be repositioned so the avgwater will be more accurate.  *Personally not 
           a big fan of this.

**Comment by ibnullify** [comment]
I created a grid, so this issue is almost resolved, but I don't think we should force the player to grow plants only in the center of a gridblock. I think we should incorporate the part in your second option where if two plants connect, they start to decrease.
