### ISSUE TITLE
Plants Drain Water

### ISSUE THREAD

**Issue by yuyangz** [yuyangz/CareBears#3]
We need to figure out a way to decrease the amount of water in each block as we place more plants.
Currently we have avgwater as a local variable in showRain(). However, since we are using avgwater for almost all plant related growth/positioning, it might be better to make an ArrayList for avgwater or something similar so that we can check the avgwater in each block more easily.

**Comment by ibnullify** [comment]
A lot of progress has been made on this. Plants decrease water in the surrounding area, which is made clear by the resized grid. The idea of an ArrayList is still possible, but likely unnecessary
